#!/bin/sh
: '
Copyright 2019 NXP
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holders nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS  AND CONTRIBUTORS
``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR
CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'
set -x
# /etc/init.d/first_run
ifconfig fm1-mac6 0.0.0.0 up
ifconfig fm1-mac1 0.0.0.0 up
ifconfig fm1-mac10 0.0.0.0 up
ifconfig wlP1p1s0 up
brctl addbr br0
brctl addif br0 fm1-mac6 fm1-mac1 fm1-mac10 
ifconfig br0 192.168.99.1 up
sed -i '5d' /etc/hostapd.conf
var=`ifconfig fm1-mac6 | awk '/ether/ {printf $2}' | awk 'BEGIN{FS=":"; OFS=":"} {print $5,$6}'`
sed -i "5i\\ssid=FRWY-LS1046A-$var" /etc/hostapd.conf
sed -n 5p /etc/hostapd.conf > /etc/ssidname
killall dnsmasq
echo adxl34x 0x1d > /sys/bus/i2c/devices/i2c-4/new_device
redis_server=`ps -ef | grep redis-server | grep -v grep`
if [ -z "$redis_server" ];
then
	/usr/bin/redis-server /etc/redis/redis.conf &
fi
netdat=`ps -ef | grep netdata | grep -v grep`
if [ -z "$netdat" ];
then
	     /usr/sbin/netdata -D &
     fi
sleep 18
systemctl unmask hostapd.service
sleep 2
/etc/init.d/hostapd start 
/usr/sbin/dnsmasq -C /etc/dnsmasq.conf &
exit 0
